# fly.toml app configuration file generated for hack-tycoon on 2026-02-15T23:58:57+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hack-tycoon'
primary_region = 'sjc'

[build]

[env]
  NODE_ENV = 'production'

[[mounts]]
  source = 'hack_tycoon_data'
  destination = '/data'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
