# fly.toml app configuration file generated for hack-tycoon on 2026-02-15T23:58:57+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hack-tycoon'
primary_region = 'sjc'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[experimental]
  auto_rollback = true

[build]

[env]
  NODE_ENV = 'production'

[[mounts]]
  source = 'hack_tycoon_data'
  destination = '/data'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
